[project]
name = "sketches"
version = "2024.01.01"
description = "Sketch a day, 2024 edition"
authors = [
    {"name" = "Erico Andrei", "email" = "ericof@gmail.com"},
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "py5==0.10.2a0",
    "CairoSVG==2.7.1",
    "opencv-python==4.10.0.84",
    "pymunk==6.8.1",
    "scikit-learn==1.5.1",
    "prettyconf==2.2.1",
    "click==8.1.7",
    "requests==2.32.3",
    "gitpython==3.1.43",
    "shapely==2.0.6",
    "trimesh==4.4.9",
    "opensimplex==0.4.5.1",
    "install-jdk==1.1.0",
]

[project.scripts]
sketches = 'utils.cli.cli:cli'

[tool.hatch.envs.default]
installer = "uv"
dependencies = [
    "black==24.8.0",
    "isort==5.13.2",
    "pre-commit==3.8.0",
    "hatchling==1.25.0",
]

[tool.hatch.envs.default.scripts]
create-today = "sketches create today"
publish-today = "sketches all today"
check = [
  "pre-commit run -a"
]

[tool.black]
target-version = ["py311"]

[tool.isort]
profile = "black"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
